export enum TEMPLATE_TYPES {
  ADMIN_STANDARD_TEMPLATE = "ADMIN_STANDARD_TEMPLATE",
  BULK_EDIT_TEMPLATES = "BULK_EDIT_TEMPLATES",
}

export enum MediaUpload {
  BULK_UPLOAD = "BULK_UPLOAD",
  ADMIN_BULK_EDIT_UPLOAD = "ADMIN_BULK_EDIT_UPLOAD",
}
